use_frameworks!

platform :ios, '8.0'

target 'LKLTableView_Example' do
  pod 'LKLTableView', :path => '../'

  target 'LKLTableView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
